version: "2"

services:
  notebook:
    build: ./machines/notebook
    ports:
      - 8888:8888
    networks:
      - cluster-net
    links:
      - spark_master
    volumes_from:
      - notebook_data

  notebook_data:
    image: busybox
    command: /bin/true
    volumes:
      - /home/compute

  spark_master:
    build: ./machines/spark/master
    container_name: spark_master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: spark_master
    networks:
      - cluster-net
    environment:
      - "constraint:node==spark_master"
      - "SPARK_CONF_DIR: /conf"
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/usr/local/spark/data

  spark_worker:
    build: ./machines/spark/worker
    container_name: spark_worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark_master:7077
    hostname: spark_worker
    networks:
      - cluster-net
    environment:
      - "constraint:node==spark_worker"
      - "SPARK_CONF_DIR: /conf"
    links:
      - spark_master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8081
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/usr/local/spark/data

networks:
  cluster-net:
    driver: overlay
