version: "2"
services:
  notebook:
    image: auser/opencv
    ports:
      - 8888:8888
    volumes:
      - .:/opt/compute

  jobmanager:
    image: biggis/flink:1.1.1
    ports:
      - "48081:8081"
    command: jobmanager
    volumes:
      - /opt/flink/conf

  taskmanager:
    image: biggis/flink:1.1.1
    depends_on:
      - jobmanager
    command: taskmanager
    volumes_from:
      - jobmanager:ro


  zookeeper:
    image: confluent/zookeeper
    ports:
        - 2181
 
  kafka:
    image: auser/kafka
    ports:
        - "9092:9092"
    links:
        - zookeeper
    environment:
        KAFKA_LOG_CLEANUP_POLICY: compact
        KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100