ersion: "2"
services:
  notebook:
    image: auser/opencv
    ports:
      - 8888:8888
    volumes:
      - .:/opt/compute
  jobmanager:
    image: flink
    ports:
      - "48081:8081"
    command: jobmanager
    volumes:
      - /opt/flink/conf

  taskmanager:
    image: flink
    depends_on:
      - jobmanager
    command: taskmanager
    volumes_from:
      - jobmanager:ro